runtime: python310

handlers:
- url: /
  static_files: pages/index.html
  upload: pages/index.html

- url: /assets
  static_dir: assets

- url: /styles
  static_dir: styles

- url: /(.*\.html)$
  static_files: pages/\1
  upload: pages/(.*\.html)$
